config/routes.rb
Rails.application.routes.draw do
  resources :domaines
  resources :filieres
 
  resources :centres
  resources :juris
  resources :students
  
  resources :users do
    member do
      get :definir_profil
    end
  end
  resources :authors
  resources :matieres
  resources :seris
  resources :niveaus
  resources :etablissements
  resources :departements
  resources :regions
  resources :countries
  resources :type_exercices
  resources :exercices
  resources :lecons
  resources :topics, only: [:index, :show]
  get '/check.txt', to: proc {[200, {}, ['HUWAL_FATHUL_ALIIMUL_GREIY']]}
  #get 'topics/index'
  #get 'topics/show'
  #resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'Login', sign_out: 'Logout', sign_up: 'Register'}, controllers:{sessions: 'users/sessions'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  resources :tags
  resources :topics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #mount ActionCable.server => '/cable'


  root to: 'blogs#index'
end

app/models/domaine.rb
class Domaine < ApplicationRecord
    belongs_to :filiere
    has_many :blogs
    #has_many :blogs, :through => :blog_domaines

    validates_presence_of :name, :filiere_id, :niveau_id
end

app/controllers/domaines_controller.rb
class DomainesController < ApplicationController
  before_action :set_domaine, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all
layout "general-layout"
  # GET /domaines
  def index
    @domaines = Domaine.all
  end

  # GET /domaines/1
  def show
  end

  # GET /domaines/new
  def new
    @domaine = Domaine.new
  end

  # GET /domaines/1/edit
  def edit
  end

  # POST /domaines
  def create
    @domaine = Domaine.new(domaine_params)

    if @domaine.save
      redirect_to @domaine, notice: 'Domaine was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /domaines/1
  def update
    if @domaine.update(domaine_params)
      redirect_to @domaine, notice: 'Domaine was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /domaines/1
  def destroy
    @domaine.destroy
    redirect_to domaines_url, notice: 'Domaine was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domaine
      @domaine = Domaine.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def domaine_params
      params.require(:domaine).permit(:name, :niveau_id, :filiere_id)
    end
end

app/helpers/domaines_helper.rb
module DomainesHelper
end

app/views/domaines/_form.html.erb
<div class="col-sm-8 blog-main">
  <%= form_with(model: domaine, local: true) do |form| %>
    <% if domaine.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(domaine.errors.count, "error") %> prohibited this domaine from being saved:</h2>

        <ul>
        <% domaine.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class:"form-control col-md-4" %>
    </div>

    <div class="form-group">
      <%= form.label :filiere_id %>
      <%= form.collection_select(:filiere_id, Filiere.all, :id, :name,
          {
            #selected: blog.topic_id,
            include_blank: true
          },
          class: 'form-control col-md-4'
        ) 
      %>
    </div>

    <div class="form-group">
      <%= form.label :niveau_id %>
      <%= form.collection_select(:niveau_id, Niveau.all, :id, :name,
          {
            #selected: blog.topic_id,
            include_blank: true
          },
          class: 'form-control col-md-4'
        ) 
      %>
    </div>

    <div class="form-group">
      <%= form.submit class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/domaines/edit.html.erb
<div class="col-sm-8 blog-main">
    <h1>Editing Domaine</h1>

    <%= render 'form', domaine: @domaine %>

    <%= link_to 'Show', @domaine %> |
    <%= link_to 'Back', domaines_path %>
</div>

app/views/domaines/index.html.erb
<div class="col-sm-8 blog-main">
  <p id="notice"><%= notice %></p>

  <h1>Domaines</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @domaines.each do |domaine| %>
        <tr>
          <td><%= domaine.name %></td>
          <td><%= link_to 'Show', domaine %></td>
          <td><%= link_to 'Edit', edit_domaine_path(domaine) %></td>
          <td><%= link_to 'Destroy', domaine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Domaine', new_domaine_path %>

</div>

app/views/domaines/new.html.erb
<div class="col-sm-8 blog-main">
    <h1>New Domaine</h1>

    <%= render 'form', domaine: @domaine %>

    <%= link_to 'Back', domaines_path %>

</div>

app/views/domaines/show.html.erb
<div class="col-sm-8 blog-main">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Domaine:</strong>
    <%= @domaine.name %>
  </p>

  <p>
    <ul>
      <% @domaine.blogs.each do |blog|%>
      <li>
        <%= link_to blog.title, blog_path(blog)%>
      </li>
      <% end %>
    <ul>
  </p>

<%if logged_in?(:site_admin)%>
	<%= link_to 'Edit', edit_domaine_path(@domaine) %> |
  <%= link_to 'Back', domaines_path %>
<%end%>
</div>