config/routes.rb
Rails.application.routes.draw do
  resources :domaines
  resources :filieres
 
  resources :centres
  resources :juris
  resources :students
  
  resources :users do
    member do
      get :definir_profil
    end
  end
  resources :authors
  resources :matieres
  resources :seris
  resources :niveaus
  resources :etablissements
  resources :departements
  resources :regions
  resources :countries
  resources :type_exercices
  resources :exercices
  resources :lecons
  resources :topics, only: [:index, :show]
  get '/check.txt', to: proc {[200, {}, ['HUWAL_FATHUL_ALIIMUL_GREIY']]}
  #get 'topics/index'
  #get 'topics/show'
  #resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'Login', sign_out: 'Logout', sign_up: 'Register'}, controllers:{sessions: 'users/sessions'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  resources :tags
  resources :topics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #mount ActionCable.server => '/cable'


  root to: 'blogs#index'
end

app/models/lecon.rb
class Lecon < ApplicationRecord
end

app/controllers/lecons_controller.rb
class LeconsController < ApplicationController
  before_action :set_lecon, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /lecons
  def index
    @lecons = Lecon.all
  end

  # GET /lecons/1
  def show
  end

  # GET /lecons/new
  def new
    @lecon = Lecon.new
  end

  # GET /lecons/1/edit
  def edit
  end

  # POST /lecons
  def create
    @lecon = Lecon.new(lecon_params)

    if @lecon.save
      redirect_to @lecon, notice: 'Lecon was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /lecons/1
  def update
    if @lecon.update(lecon_params)
      redirect_to @lecon, notice: 'Lecon was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /lecons/1
  def destroy
    @lecon.destroy
    redirect_to lecons_url, notice: 'Lecon was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecon
      @lecon = Lecon.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def lecon_params
      params.require(:lecon).permit(:title, :body)
    end
end

app/helpers/lecons_helper.rb
module LeconsHelper
end

app/views/lecons/_form.html.erb
<%= form_with(model: lecon, local: true) do |form| %>
  <% if lecon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lecon.errors.count, "error") %> prohibited this lecon from being saved:</h2>

      <ul>
      <% lecon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lecons/edit.html.erb
<h1>Editing Lecon</h1>

<%= render 'form', lecon: @lecon %>

<%= link_to 'Show', @lecon %> |
<%= link_to 'Back', lecons_path %>

app/views/lecons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lecons</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lecons.each do |lecon| %>
      <tr>
        <td><%= lecon.title %></td>
        <td><%= lecon.body %></td>
        <td><%= link_to 'Show', lecon %></td>
        <td><%= link_to 'Edit', edit_lecon_path(lecon) %></td>
        <td><%= link_to 'Destroy', lecon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecon', new_lecon_path %>

app/views/lecons/new.html.erb
<h1>New Lecon</h1>

<%= render 'form', lecon: @lecon %>

<%= link_to 'Back', lecons_path %>

app/views/lecons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @lecon.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @lecon.body %>
</p>

<%= link_to 'Edit', edit_lecon_path(@lecon) %> |
<%= link_to 'Back', lecons_path %>