config/routes.rb
Rails.application.routes.draw do
  resources :domaines
  resources :filieres
 
  resources :centres
  resources :juris
  resources :students
  
  resources :users do
    member do
      get :definir_profil
    end
  end
  resources :authors
  resources :matieres
  resources :seris
  resources :niveaus
  resources :etablissements
  resources :departements
  resources :regions
  resources :countries
  resources :type_exercices
  resources :exercices
  resources :lecons
  resources :topics, only: [:index, :show]
  get '/check.txt', to: proc {[200, {}, ['HUWAL_FATHUL_ALIIMUL_GREIY']]}
  #get 'topics/index'
  #get 'topics/show'
  #resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'Login', sign_out: 'Logout', sign_up: 'Register'}, controllers:{sessions: 'users/sessions'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  resources :tags
  resources :topics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #mount ActionCable.server => '/cable'


  root to: 'blogs#index'
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :user
  belongs_to :etablissement
  belongs_to :matiere

  has_many	 :blogs

  validates_presence_of :telephone, :user_id, :etablissement_id, :matiere_id
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status:{draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body, :niveau_id, :domaine_id, :filiere_id, :user_id, :tag_list #, :author_id,
  #belongs_to :topic, optional: true
  belongs_to :author, optional: true
  belongs_to :niveau
  belongs_to :seri, optional: true
  belongs_to :matiere, optional: true
  belongs_to :filiere
  belongs_to :domaine
  belongs_to :user
  
  #has_many :blog_domaines
  #has_many :domaines, :through => :blog_domaines
  has_many :comments, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings

  has_one_attached :image
  #mount_uploader :image, BlogUploader

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end
  
  def tag_list=(tags_string)
    #tags.join(", ")
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect {|name| Tag.find_or_create_by(name: name)}
    self.tags = new_or_found_tags
  end

  def self.special_blogs
  	all
  end

  def self.featured_blogs
  	limit(3)
  end

  def self.recent
    order("created_at DESC")
  end

  def self.owner(user)
    Blog.all.where(author_id: user.authors.ids)
  end

  def prov_princens
    Blog.all.where(author_id: user.authors.ids)
  end
  #if logged_in?(:professeur) and current_user.id.authors.empty? #for User with no authors 
end

app/models/centre.rb
class Centre < ApplicationRecord
    has_many :juris
    has_many :students

    belongs_to :departement
    
    validates_presence_of :numcentre, :departement_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog

  validates :content, presence: true, length: { minimum: 5, maximimum: 1000 }

  after_create_commit { CommentBroadcastJob.perform_later(self) }
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :regions
    has_many :responszone

    validates_presence_of :name
end

app/models/domaine.rb
class Domaine < ApplicationRecord
    belongs_to :filiere
    has_many :blogs
    #has_many :blogs, :through => :blog_domaines

    validates_presence_of :name, :filiere_id, :niveau_id
end

app/models/exercice.rb
class Exercice < ApplicationRecord
	validates_presence_of :title, :introduction, :developpement, :conclusion
end

app/models/filiere.rb
class Filiere < ApplicationRecord
    #BELONGS TO
    belongs_to :niveau

    #HAS MANY
    has_many :domaines
    has_many :blogs

    validates_presence_of :name, :niveau_id
end

app/models/juri.rb
class Juri < ApplicationRecord
    belongs_to :centre

    validates_presence_of :numjuri, :centre_id
end

app/models/lecon.rb
class Lecon < ApplicationRecord
end

app/models/matiere.rb
class Matiere < ApplicationRecord
  belongs_to :niveau
  belongs_to :seri
  has_many   :blogs
end

app/models/niveau.rb
class Niveau < ApplicationRecord
	has_many :seris
	has_many :matieres
	has_many :students
	has_many :filieres
	has_many :blogs

	validates_presence_of :name,  :abbrege
	def self.with_blogs
  	#includes(:blogs).where.not(blogs: {id: nil})
  end
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :country
  
  has_many :departements, dependent: :destroy
  has_many :ouvrier, dependent: :destroy
  has_many :responszones

  validates_presence_of :name, :country_id 

  # Methode Determinant Region En Fonction Du Responsable
  def by_respons_zone(id_responszone)
      Region.all.where(id: id_responszone)
  end


end

app/models/seri.rb
class Seri < ApplicationRecord
  belongs_to :niveau
  has_many   :matieres
  has_many   :students

  validates_presence_of :name, :niveau_id

end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized

  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.image_generator(height:'250', width:'250')
  end
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :etablissement
    belongs_to :centre
    belongs_to :niveau
    belongs_to :seri
    #belongs_to :departement, optional: true
    #belongs_to :region, optional: true

    validates_presence_of :nom, :prenom, :cni, :telephone, :numtable, :email, :etablissement_id, :niveau_id, :seri_id, :juri_id, :centre_id
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :blogs, through: :taggings

    def to_s
        name
    end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :blog
  belongs_to :tag
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs

  def self.with_blogs
  	includes(:blogs).where.not(blogs: {id: nil})
  end
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin, :trusted, :respons_zone, :professeur, :principale, :censeur, :proviseur], multiple: false)                                      ##
  ############################################################################################ 

  # Les roles site_admin Et trusted Sont A Donner Uniquement Par L'Administrateur 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   validates_presence_of :name
   
   #belongs_to :privilege
   has_many :comments, dependent: :destroy
   has_many :blogs, dependent: :destroy
   has_many :authors, dependent: :destroy
   #has_many :responszones, dependent: :destroy
   #has_many :ouvriers
   #has_many :metiers
   has_many :departements
  def first_name
  	self.name.split.first
  end

  def last_name
  	self.name.split.last
  end

  def set_to_profil(profil)
    self.update!(roles:profil)
  end

  def self.recent
    order("created_at ASC")
  end
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
	<div class="inner">
	  <p class="app-footer"><%= copyright_generator %>.</p>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">SK8Z-_-CLBK</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
	<p>
		<p>Cultivons le Savoir pour le bien de tous</p>
		<%= copyright_generator %>
	</p>
	<p>
	  <a href="#">Back to top</a>
	</p>
</footer>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light blog-nav">
  <div class="container">
    <h1><%= link_to "CLBK", root_path, class: 'navbar-brand policy' %></h1>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
 
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
     <ul class="navbar-nav ml-auto">
       <%= nav_helper 'nav-link', 'span' %>
       <%= login_helper 'nav-link' %>
     </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
  <div class="col-sm-3 offset-sm-1 blog-sidebar">
  <% unless current_user.is_a?(GuestUser) %>
    <%= render partial: 'blogs/admin_configuration' %>
  <% end %>
  <p></p>
  <div class="sidebar-module sidebar-module-inset">
    <h4><u>CLBK</u></h4>
    <p><b>Notice: </b><em>Apprendre n'est pas facile mais peut bien être simple</em>...</p>
  </div>

  <%= source_helper("alert alert-info blog-sidebar-source") %>
  
  <div class="sidebar-module">
  <h1><u>Référenciels</u></h1>
    <h4><%= link_to "Blogs", blogs_path() %></h4>
    <h4><%= link_to "Niveaux", niveaus_path() %></h4>
    <h4><%= link_to "Filiéres", niveaus_path() %></h4>
    <h4><%= link_to "Domaines", niveaus_path() %></h4>
    
  </div>
  <div class="sidebar-module">
    <h4></h4>
    <ol class="list-unstyled">
      <li><a href="#"><%= fa_icon "github 3x" %></a></li>
      <li><a href="#"><%= fa_icon "facebook 3x" %></a></li>
      <li><a href="#"><%= fa_icon "instagram 3x" %></a></li>
      <li><a href="https://twitter.com/home", target="_blanc"><%= fa_icon "twitter 3x" %></a></li>
    </ol>
  </div>
</div><!-- /.end sidebar -->

app/views/shared/_exercice_footer.html.erb
<footer class="blog-footer">
	<p>
		<%= copyright_generator %>
	</p>
	<p>
	  <a href="#">Back to top</a>
	</p>
</footer>

app/views/shared/_exercice_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Exercices</h1>
    <p class="lead blog-description">Les exercices pour chaque niveau</p>
    <span>
    	<%= link_to 'Rediger une exercice', new_exercice_path() if logged_in?(:site_admin) %>
    </span>

    <span>
    	<%#= link_to 'Topics', topics_path %>
    </span>
    
  </div>
</div>

app/views/shared/_exercice_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light blog-nav">
  <div class="container">
    <%= link_to "ZICROU SK8Z", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
 
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
     <ul class="navbar-nav ml-auto">
       <%= nav_helper 'nav-link', 'span' %>
       <%= login_helper 'nav-link' %>
     </ul>
    </div>
  </div>
</nav>

app/views/shared/_exercice_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <%= source_helper("alert alert-info blog-sidebar-source") %>
  
  <div class="sidebar-module">
    <h4>Topics</h4>
    <% #@side_bar_topics.each do |topic|%>
      <p><%#= link_to topic.title, topic_path(topic) %></p>
    <%# end %>
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled">
      <li><a href="#"><%= fa_icon "github 3x" %></a></li>
      <li><a href="#"><%= fa_icon "facebook 3x" %></a></li>
      <li><a href="https://twitter.com/home", target="_blanc"><%= fa_icon "twitter 3x" %></a></li>
      <li><a href="#"><%= fa_icon "instagram 3x" %></a></li>
    </ol>
  </div>
</div><!-- /.end sidebar -->

app/views/shared/_g_l_sidebar.html.erb
<div class="col-sm-3 offset-sm-8 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4><u>CLBK</u></h4>
  </div>

  <%= source_helper("alert alert-info blog-sidebar-source") %>
  
  <div class="sidebar-module">
    <h4>Paramétrage</h4>
    <%= link_to "Users", users_path()%>
    <%= link_to "ResponsZones", responszones_path()%>
    <%= link_to "Metiers", metiers_path()%>
    <%= link_to "Domaines", domaines_path()%>
    <%= link_to "Departments", departements_path()%>
    <%= link_to "Regions", regions_path()%>
    <%= link_to "Pays", countries_path()%>
    <%= link_to "Centres", centres_path()%>
    <p></p>
    <p>dipbnflòjokfn</p>
    <%# @side_bar_topics.each do |topic|%>
      <p><%#= link_to 'les cours de '+ topic.title, topic_path(topic) %></p>
    <%# end %>
  </div>
  <div class="sidebar-module">
    <h4></h4>
    <ol class="list-unstyled">
      <li><a href="#"><%= fa_icon "github 3x" %></a></li>
      <li><a href="#"><%= fa_icon "facebook 3x" %></a></li>
      <li><a href="https://twitter.com/home", target="_blanc"><%= fa_icon "twitter 3x" %></a></li>
      <li><a href="#"><%= fa_icon "instagram 3x" %></a></li>
    </ol>
  </div>
</div><!-- /.end sidebar -->

app/views/shared/_nav.html.erb
<div class="<% location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%#= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
        <footer class="text-muted">
      <div class="container">
        <p class="float-right">
        	<%= link_to 'View All Portfolios', portfolios_path %> /
         	<a href="#">Back to top</a>
        </p>

        <p>
        	<%= copyright_generator %>
        </p>
      </div>
    </footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <%= link_to 'Find Out More About Me!', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog!', blogs_path, class: 'btn btn-secondary' %>
    </p>
    <hr>
    <p>Hope You fully enjoy Drag ans Drop: Yes You can try whit these Photos!!!</p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">I am me, through differents ways, but the same me; The same style! The Same Zicrou!.</p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Zicrou</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>