config/routes.rb
Rails.application.routes.draw do
  resources :domaines
  resources :filieres
 
  resources :centres
  resources :juris
  resources :students
  
  resources :users do
    member do
      get :definir_profil
    end
  end
  resources :authors
  resources :matieres
  resources :seris
  resources :niveaus
  resources :etablissements
  resources :departements
  resources :regions
  resources :countries
  resources :type_exercices
  resources :exercices
  resources :lecons
  resources :topics, only: [:index, :show]
  get '/check.txt', to: proc {[200, {}, ['HUWAL_FATHUL_ALIIMUL_GREIY']]}
  #get 'topics/index'
  #get 'topics/show'
  #resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'Login', sign_out: 'Logout', sign_up: 'Register'}, controllers:{sessions: 'users/sessions'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  resources :tags
  resources :topics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #mount ActionCable.server => '/cable'


  root to: 'blogs#index'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :blogs, through: :taggings

    def to_s
        name
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all
layout 'general-layout'
  # GET /tags
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to @tag, notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to @tag, notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_to tags_url, notice: 'Tag was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<div class="col-sm-8 blog-main">
  <%= form_with(model: tag, local: true) do |form| %>
    <% if tag.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

        <ul>
        <% tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, clas:"form-control col-md-4" %>
    </div>

    <div class="form-group">
      <%= form.submit class:"btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/tags/edit.html.erb
<div class="col-sm-8 blog-main">
    <h1>Editing Tag</h1>

    <%= render 'form', tag: @tag %>

    <%= link_to 'Show', @tag %> |
    <%= link_to 'Back', tags_path %>
</div>

app/views/tags/index.html.erb
<div class="col-sm-8 blog-main">
  <p id="notice"><%= notice %></p>

  <h1>Tags</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tags.each do |tag| %>
        <tr>
          <td><%= tag.name %></td>
          <td><%= link_to 'Show', tag %></td>
          <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
          <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Tag', new_tag_path %>
</div>

app/views/tags/new.html.erb
<div class="col-sm-8 blog-main">
    <h1>New Tag</h1>

    <%= render 'form', tag: @tag %>

    <%= link_to 'Back', tags_path %>
</div>

app/views/tags/show.html.erb
<div class="col-sm-8 blog-main">
  <p id="notice"><%= notice %></p>

  <h1>
    <strong>Tag:</strong>
    <%= @tag.name %>
  </h1>

  <p>
    <ul>
      <% @tag.blogs.each do |blog|%>
      <li>
        <%= link_to blog.title, blog_path(blog)%>
      </li>
      <% end %>
    <ul>
  </p>

  <%# if logged_in?(:site_admin) %>
    <%#= link_to 'Edit(tag)', edit_tag_path(@tag) %> 
    <%#= link_to 'Back', tags_path %>
  <% #end %>
</div>